<?php

namespace AppBundle\Repository;

/**
 * BieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BieresRepository extends \Doctrine\ORM\EntityRepository
{
}
